services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
        - ${ROOT_SERVER_CONFIG}/portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - homepage.group=Admin
      - homepage.name=Portainer
      - homepage.icon=sh-portainer.png
      - homepage.href=http://portainer.alexball.uk
      - homepage.description=Docker container manager

  # hbbs:
  #   container_name: hbbs
  #   image: rustdesk/rustdesk-server:latest
  #   command: hbbs
  #   volumes:
  #     - ${ROOT_SERVER_CONFIG}/rustdesk/hbbs:/root
  #   network_mode: "host"

  #   depends_on:
  #     - hbbr
  #   restart: unless-stopped

  # hbbr:
  #   container_name: hbbr
  #   image: rustdesk/rustdesk-server:latest
  #   command: hbbr
  #   volumes:
  #     - ${ROOT_SERVER_CONFIG}/rustdesk/hbbr:/root
  #   network_mode: "host"
  #   restart: unless-stopped
