services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
        - /home/alex/Servers/portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - homepage.group=Admin
      - homepage.name=Portainer
      - homepage.icon=sh-portainer.png
      - homepage.href=http://portainer.alexball.uk
      - homepage.description=Docker container manager

  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - /home/alex/Servers/Caddy/conf:/etc/caddy
      - /home/alex/Servers/Caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config

  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    network_mode: bridge
    ports:
      - 8000:8000/tcp
    volumes:
      - /home/alex/Servers/ddns-updater/data:/updater/data
    environment:
      - CONFIG=
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIPV6_HTTP_PROVIDERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - HTTP_TIMEOUT=10s

      # Web UI
      - LISTENING_ADDRESS=:8000
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_LEVEL=info
      - LOG_CALLER=hidden
      - SHOUTRRR_ADDRESSES=
    restart: always
    labels:
      - homepage.group=Admin
      - homepage.name=DDNS-Updater
      - homepage.icon=sh-portainer.png
      - homepage.href=http://ddns.alexball.uk
      - homepage.description=DDNS Updater

volumes:
  caddy_data:
  caddy_config:

