services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - JELLYFIN_PublishedServerUrl=http://jellyfin.alexball.uk
    volumes:
      -  /mnt/c/Servers/jellyfin/library:/config
      -  media_share:/data
    ports:
      - 8096:8096
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=sh-jellyfin.png
      - homepage.href=http://jellyfin.alexball.uk
      - homepage.description=Media server
    
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - /mnt/c/Servers/sonarr/data:/config
      - media_share:/data
      - ${DOWNLOAD_LOCATION}:/data/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    labels:
      - homepage.group=Admin
      - homepage.name=Sonarr
      - homepage.icon=sh-sonarr.png
      - homepage.href=http://sonarr.alexball.uk
      - homepage.description=TV Show fetcher
    
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - /mnt/c/Servers/radarr/data:/config
      - media_share:/data
      - ${DOWNLOAD_LOCATION}:/data/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      - homepage.group=Admin
      - homepage.name=Radarr
      - homepage.icon=sh-radarr.png
      - homepage.href=http://radarr.alexball.uk
      - homepage.description=Movie fetcher
    
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - /mnt/c/Servers/readarr/data:/config
      - media_share:/books
      - ${DOWNLOAD_LOCATION}:/data/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
    labels:
      - homepage.group=Admin
      - homepage.name=Readarr
      - homepage.icon=sh-readarr.png
      - homepage.href=http://readarr.alexball.uk
      - homepage.description=Book & Audiobook fetcher

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - /mnt/c/Servers/bazarr/config:/config
      - media_share:/data
    ports:
      - 6767:6767
    restart: unless-stopped
    labels:
      - homepage.group=Admin
      - homepage.name=Bazarr
      - homepage.icon=sh-bazarr.png
      - homepage.href=http://bazarr.alexball.uk
      - homepage.description=Subtitle fetcher
    
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    volumes:
      -  /mnt/c/Servers/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    labels:
      - homepage.group=Admin
      - homepage.name=Prowlarr
      - homepage.icon=sh-prowlarr.png
      - homepage.href=http://prowlarr.alexball.uk
      - homepage.description=Indexer fetcher
    
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    volumes:
      -  /mnt/c/Servers/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
    labels:
      - homepage.group=Admin
      - homepage.name=Ombi
      - homepage.icon=sh-ombi.png
      - homepage.href=http://ombi.alexball.uk
      - homepage.description=Content Requester
    
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /mnt/c/Servers/qbittorrent/appdata:/config
      - ${DOWNLOAD_LOCATION}:/data/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    labels:
      - homepage.group=Admin
      - homepage.name=QBittorent
      - homepage.icon=sh-qbittorrent.png
      - homepage.href=http://qb.alexball.uk
      - homepage.description=Torrent downloader
    
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - PUID=0
      - PGID=0 
    ports:
      - 13378:80
    volumes:
      - media_share:/data
      - /mnt/c/Servers/audiobookshelf/config:/config
      - /mnt/c/Servers/audiobookshelf/metadata:/metadata
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=AudioBookshelf
      - homepage.icon=sh-audiobookshelf.png
      - homepage.href=http://audiobookshelf.alexball.uk
      - homepage.description=Audiobook Server
      
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    pid: host
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock
    environment:
      - "GLANCES_OPT=-w"
    #ports:
    #  - 61208:61208
    labels:
      - homepage.group=Admin
      - homepage.name=Glances
      - homepage.icon=sh-glances.png
      - homepage.href=http://glances.alexball.uk
      - homepage.description=Server Details
      
      
  crafty:
    container_name: crafty
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: unless-stopped
    ports:
        - "8443:8443" # HTTPS
        - "8123:8123" # DYNMAP
        - "19132:19132/udp" # BEDROCK
        - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - /mnt/e/crafty:/crafty/backups
        - /mnt/e/crafty:/crafty/logs
        - /mnt/e/crafty:/crafty/servers
        - /mnt/e/crafty:/crafty/app/config
        - /mnt/e/crafty:/crafty/import
    labels:
      - homepage.group=Admin
      - homepage.name=Crafty
      - homepage.icon=sh-crafty-controller.png
      - homepage.href=http://crafty.alexball.uk
      - homepage.description=Minecraft server manager
    
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:latest
    restart: unless-stopped
    ports:
      - 5690:5690
    volumes:
      - /mnt/c/Servers/wizarr/database:/data/database
    labels:
      - homepage.group=Admin
      - homepage.name=Wizarr
      - homepage.icon=sh-wizarr.png
      - homepage.href=http://wizarr.alexball.uk
      - homepage.description=Server invite manager

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
    ports:
      - 5055:5055
    volumes:
      - /mnt/c/Servers/jellyseerr:/app/config
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=JellySeerr
      - homepage.icon=sh-jellyseerr.png
      - homepage.href=http://jellyseerr.alexball.uk
      - homepage.description=Content Requester
      
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    ports:
        - "9925:9000"
    volumes:
      - /mnt/c/Servers/mealie:/app/data/
    environment:
      ALLOW_SIGNUP: "false"
      BASE_URL: https://mealie.alexball.uk
    labels:
      - homepage.group=Media
      - homepage.name=Mealie
      - homepage.icon=sh-mealie.png
      - homepage.href=http://mealie.alexball.uk
      - homepage.description=Recipe Database

  lurker:
    image: ghcr.io/oppiliappan/lurker:latest
    container_name: lurker
    volumes:
      - /mnt/c/Servers/lurker:/data
    ports:
      - "3333:3000"
    labels:
      - homepage.group=Media
      - homepage.name=Lurker
      - homepage.icon=sh-lurker.png
      - homepage.href=http://lurker.alexball.uk
      - homepage.description=Alt Reddit Frontend
      
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - PUID=1001
      - PGID=1001
    ports:
      - 3000:3000
    volumes:
      - /mnt/c/Servers/homepage/config:/app/config
      - media_share:/data
    restart: unless-stopped
    
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped
    
volumes:
  media_share:
    driver: local
    driver_opts:
      type: cifs
      o: "username=,password=,vers=1.0,uid=1001,gid=1001"
      device: "//192.168.1.211/6TB Share"
