services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    #runtime: nvidia
    environment:
      - PUID=0
      - PGID=0
      - JELLYFIN_PublishedServerUrl=http://jellyfin.alexball.uk
    #  - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      -  ${ROOT_SERVER_CONFIG}/jellyfin/library:/config
      -  ${ROOT_SERVER_CONFIG}/jellyfin/web-config.json:/usr/share/jellyfin/web/config.json
      -  media_share:/data
    ports:
      - 8096:8096
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=sh-jellyfin.png
      - homepage.href=http://jellyfin.alexball.uk
      - homepage.description=Media server
    
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
    volumes:
      - ${ROOT_SERVER_CONFIG}/sonarr/data:/config
      - media_share:/data/STORAGE
      - ${DOWNLOAD_LOCATION}:/data/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    labels:
      - homepage.group=Admin
      - homepage.name=Sonarr
      - homepage.icon=sh-sonarr.png
      - homepage.href=http://sonarr.alexball.uk
      - homepage.description=TV Show fetcher
    
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
    volumes:
      - ${ROOT_SERVER_CONFIG}/radarr/data:/config
      - media_share:/data/STORAGE
      - ${DOWNLOAD_LOCATION}:/data/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      - homepage.group=Admin
      - homepage.name=Radarr
      - homepage.icon=sh-radarr.png
      - homepage.href=http://radarr.alexball.uk
      - homepage.description=Movie fetcher
    
  # readarr:
  #   image: lscr.io/linuxserver/readarr:develop
  #   container_name: readarr
  #   environment:
  #     - PUID=0
  #     - PGID=0
  #   volumes:
  #     - ${ROOT_SERVER_CONFIG}/readarr/data:/config
  #     - media_share:/books
  #     - ${DOWNLOAD_LOCATION}:/data/downloads
  #   ports:
  #     - 8787:8787
  #   restart: unless-stopped
  #   labels:
  #     - homepage.group=Admin
  #     - homepage.name=Readarr
  #     - homepage.icon=sh-readarr.png
  #     - homepage.href=http://readarr.alexball.uk
  #     - homepage.description=Book & Audiobook fetcher

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - ${ROOT_SERVER_CONFIG}/bazarr/config:/config
      - media_share:/data/STORAGE
    ports:
      - 6767:6767
    restart: unless-stopped
    labels:
      - homepage.group=Admin
      - homepage.name=Bazarr
      - homepage.icon=sh-bazarr.png
      - homepage.href=http://bazarr.alexball.uk
      - homepage.description=Subtitle fetcher
    
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    volumes:
      -  ${ROOT_SERVER_CONFIG}/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    labels:
      - homepage.group=Admin
      - homepage.name=Prowlarr
      - homepage.icon=sh-prowlarr.png
      - homepage.href=http://prowlarr.alexball.uk
      - homepage.description=Indexer fetcher
    
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1001
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${ROOT_SERVER_CONFIG}/qbittorrent/appdata:/config
      - ${DOWNLOAD_LOCATION}:/data/downloads
      - media_share:/data/STORAGE
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
      - 19730:19730
    restart: unless-stopped
    labels:
      - homepage.group=Admin
      - homepage.name=QBittorent
      - homepage.icon=sh-qbittorrent.png
      - homepage.href=http://qb.alexball.uk
      - homepage.description=Torrent downloader
    
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - PUID=0
      - PGID=0 
    ports:
      - 13378:80
    volumes:
      - media_share:/data
      - ${ROOT_SERVER_CONFIG}/audiobookshelf/config:/config
      - ${ROOT_SERVER_CONFIG}/audiobookshelf/metadata:/metadata
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=AudioBookshelf
      - homepage.icon=sh-audiobookshelf.png
      - homepage.href=http://audiobookshelf.alexball.uk
      - homepage.description=Audiobook Server
      
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - ${ROOT_SERVER_CONFIG}/komga:/config
      - media_share:/data
    ports:
      - 25600:25600
    user: "1000:1000"
    environment:
      - TZ=Europe/London
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Komga
      - homepage.icon=sh-komga.png
      - homepage.href=http://komga.alexball.uk
      - homepage.description=Comic & Manga Reader
      
  # kapowarr:
  #   container_name: kapowarr
  #   image: mrcas/kapowarr:latest
  #   volumes:
  #     - "${ROOT_SERVER_CONFIG}/kapowarr-db:/app/db"
  #     - "${DOWNLOAD_LOCATION}:/app/temp_downloads"
  #     - "media_share:/comics-1"
  #   ports:
  #     - 5656:5656
  #   labels:
  #     - homepage.group=Admin
  #     - homepage.name=Kapowarr
  #     - homepage.icon=sh-kapowarr.png
  #     - homepage.href=http://kapowarr.alexball.uk
  #     - homepage.description=Comic & Manga fetcher
      
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    pid: host
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock
    environment:
      - "GLANCES_OPT=-w"
    #ports:
    #  - 61208:61208
    labels:
      - homepage.group=Admin
      - homepage.name=Glances
      - homepage.icon=sh-glances.png
      - homepage.href=http://glances.alexball.uk
      - homepage.description=Server Details
    
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:latest
    restart: unless-stopped
    ports:
      - 5690:5690
    volumes:
      - ${ROOT_SERVER_CONFIG}/wizarr/database:/data/database
    labels:
      - homepage.group=Admin
      - homepage.name=Wizarr
      - homepage.icon=sh-wizarr.png
      - homepage.href=http://wizarr.alexball.uk
      - homepage.description=Server invite manager

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
    ports:
      - 5055:5055
    volumes:
      - ${ROOT_SERVER_CONFIG}/jellyseerr:/app/config
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=JellySeerr
      - homepage.icon=sh-jellyseerr.png
      - homepage.href=http://jellyseerr.alexball.uk
      - homepage.description=Content Requester
      
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    ports:
        - "9925:9000"
    volumes:
      - ${ROOT_SERVER_CONFIG}/mealie:/app/data/
    environment:
      ALLOW_SIGNUP: "false"
      BASE_URL: https://mealie.alexball.uk
    labels:
      - homepage.group=Media
      - homepage.name=Mealie
      - homepage.icon=sh-mealie.png
      - homepage.href=http://mealie.alexball.uk
      - homepage.description=Recipe Database
           
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage:3000,localhost:3000,alexball.uk
    ports:
      - 3000:3000
    volumes:
      - ${ROOT_SERVER_CONFIG}/homepage/config:/app/config
      - media_share:/data
    restart: unless-stopped
    
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped
    
  # caddy:
  #   container_name: caddy
  #   image: caddy:latest
  #   restart: unless-stopped
  #   cap_add:
  #     - NET_ADMIN
  #   network_mode: "host"
  #   volumes:
  #     - ${ROOT_SERVER_CONFIG}/Caddy/conf:/etc/caddy
  #     - ${ROOT_SERVER_CONFIG}/Caddy/site:/srv
  #     - ${ROOT_SERVER_CONFIG}/Caddy/data:/data
  #     - ${ROOT_SERVER_CONFIG}/Caddy/config:/config
  #   environment:
  #     - SERVER_ADDRESS=192.168.1.245

  romm:
      image: rommapp/romm:latest
      container_name: romm
      restart: unless-stopped
      environment:
          - DB_HOST=romm-db
          - DB_NAME=romm # Should match MARIADB_DATABASE in mariadb
          - DB_USER=romm-user # Should match MARIADB_USER in mariadb
          - DB_PASSWD=password # Should match MARIADB_PASSWORD in mariadb
          - ROMM_AUTH_SECRET_KEY=a220cf155095de76a0f933f932cab3211ee999297c838fc06e89b557db7017de # Generate a key with `openssl rand -hex 32`
          - SCREENSCRAPER_USER=adbsjb # These are the recommended metadata providers
          - SCREENSCRAPER_PASSWORD=ytxfci7qV3wF # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#screenscraper
          - RETROACHIEVEMENTS_API_KEY=behlmSkE5ZEZTSfjkPxfNJiun4o50kZ2 # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#retroachievements
          - STEAMGRIDDB_API_KEY=8925dd44a2cb8d59f938583aa5b3c3d9 # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#steamgriddb
          - HASHEOUS_API_ENABLED=true # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#hasheous
      volumes:
          - romm_resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
          - romm_redis_data:/redis-data # Cached data for background tasks
          - ${ROOT_SERVER_CONFIG}/romm/library:/romm/library # Your game library. Check https://github.com/rommapp/romm?tab=readme-ov-file#folder-structure for more details.
          - ${ROOT_SERVER_CONFIG}/romm/assets:/romm/assets # Uploaded saves, states, etc.
          - ${ROOT_SERVER_CONFIG}/romm/config:/romm/config # Path where config.yml is stored
      ports:
          - 4545:8080
      labels:
          - homepage.group=Media
          - homepage.name=RomM
          - homepage.icon=sh-romm.png
          - homepage.href=http://romm.alexball.uk
          - homepage.description=Retro Game Server
      depends_on:
          romm-db:
              condition: service_healthy
              restart: true

  romm-db:
      image: mariadb:latest
      container_name: romm-db
      restart: unless-stopped
      environment:
          - MARIADB_ROOT_PASSWORD=password # Use a unique, secure password
          - MARIADB_DATABASE=romm
          - MARIADB_USER=romm-user
          - MARIADB_PASSWORD=password
      volumes:
          - mysql_data:/var/lib/mysql
      healthcheck:
          test: [CMD, healthcheck.sh, --connect, --innodb_initialized]
          start_period: 30s
          start_interval: 10s
          interval: 10s
          timeout: 5s
          retries: 5

  donetick:
    image: donetick/donetick
    container_name: donetick
    restart: unless-stopped
    ports:
      - 2021:2021
    volumes:
      - ${ROOT_SERVER_CONFIG}/donetick/data:/donetick-data
      - ${ROOT_SERVER_CONFIG}/donetick/config:/config
    environment:
      - DT_ENV=selfhosted
      - DT_SQLITE_PATH=/donetick-data/donetick.db
    labels:
          - homepage.group=Media
          - homepage.name=Donetick
          - homepage.icon=sh-donetick.png
          - homepage.href=http://donetick.alexball.uk
          - homepage.description=Chore list

  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - ${ROOT_SERVER_CONFIG}/calibre/config:/config
    ports:
      - 8082:8080
      - 8181:8181
      - 8081:8081
    restart: unless-stopped
    labels:
          - homepage.group=Admin
          - homepage.name=Calibre Manage
          - homepage.icon=sh-calibre.png
          - homepage.href=http://managecalibre.alexball.uk
          - homepage.description=Ebook library backend


  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ${ROOT_SERVER_CONFIG}/calibre-web/data:/config
      - ${ROOT_SERVER_CONFIG}/calibre/config/Library:/books
    ports:
      - 8083:8083
    restart: unless-stopped
    labels:
          - homepage.group=Media
          - homepage.name=Calibre Web
          - homepage.icon=sh-calibre-web.png
          - homepage.href=http://calibre.alexball.uk
          - homepage.description=Ebook library and reader
      
volumes:
  mysql_data:
  romm_resources:
  romm_redis_data:
  media_share:
    driver: local
    driver_opts:
      type: cifs
      o: "username=,password=,vers=1.0,uid=1001,gid=1001"
      device: "//192.168.1.211/6TB Share"
